<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Tspi.Sim</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Tspi.Core/Tspi.Core.csproj" />
  </ItemGroup>
</Project>
